name: Configure Workflow to use AWS IAM Role
author: Sam Anthony

# NOTE: The workflow calling this must have the following permissions configured
# permissions:
#   id-token: write
#   contents: read
# https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/

# See also https://github.com/aws-actions/configure-aws-credentials


inputs:
  role-to-assume:
    required: true
    description: A preconfigured IAM Role ARN

runs:
  using: "composite"
  steps:
  - name: Configure AWS credentials debug info
    shell: bash
    run: |
      echo "Attempting to use role '${{ inputs.role-to-assume }}'"
  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: ${{ inputs.role-to-assume }}
      role-session-name: GitHub_to_AWS_via_FederatedOIDC # I think this value is arbitrary
      aws-region: ap-southeast-2
