name: Configure Workflow to use AWS IAM Role
author: Sam Anthony

# NOTE: The workflow calling this must have the following permissions configured
# permissions:
#   id-token: write
#   contents: read
# https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/

# See also https://github.com/aws-actions/configure-aws-credentials


inputs:
  env-name:
    required: true
  ENVIRONMENT_AWS_MAPPINGS:
    required: true

outputs:
  account-id:
    account-id: ${{ steps.aws-info.outputs.account-id }}
  region:
    region: ${{ steps.aws-info.outputs.region }}
  github-oidc-role-arn:
    github-oidc-role-arn: ${{ steps.aws-info.outputs.github-oidc-role-arn }}

runs:
  using: "composite"
  steps:
  - name: Determine Region and IAM Role
    id: aws-info
    shell: bash
    env:
      ENVIRONMENT_AWS_MAPPINGS: ${{ inputs.ENVIRONMENT_AWS_MAPPINGS }}
    run: |
      ACCOUNT_ID=$(echo "${ENVIRONMENT_AWS_MAPPINGS}" | jq '."${{ inputs.env-name }}".accountId')
      REGION=$(echo "${ENVIRONMENT_AWS_MAPPINGS}" | jq '."${{ inputs.env-name }}".region')
      GITHUB_OIDC_ROLE_ARN=$(echo "${ENVIRONMENT_AWS_MAPPINGS}" | jq '."${{ inputs.env-name }}".githubOidcRoleArn')
      echo "account-id=${ACCOUNT_ID}" >> "$GITHUB_OUTPUT"
      echo "region=${REGION}" >> "$GITHUB_OUTPUT"
      echo "github-oidc-role-arn=${GITHUB_OIDC_ROLE_ARN}" >> "$GITHUB_OUTPUT"

  - name: Debug
    shell: bash
    run: |
      echo "${{ steps.aws-info.outputs.account-id }}"      

#  - name: Configure AWS credentials debug info
#    shell: bash
#    run: |
#      echo "Attempting to use role '${{ inputs.role-to-assume }}'"
#  - name: Configure AWS credentials
#    uses: aws-actions/configure-aws-credentials@v4
#    with:
#      role-to-assume: ${{ inputs.role-to-assume }}
#      role-session-name: GitHub_to_AWS_via_FederatedOIDC # I think this value is arbitrary
#      aws-region: ${{ inputs.aws-region }}
